"""empty message

Revision ID: 56a456600a04
Revises: 0819604d2663
Create Date: 2017-03-12 22:04:17.070081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56a456600a04'
down_revision = '0819604d2663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_profile', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.drop_column('user_profile', 'creationDate')
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'last_name')
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.INTEGER(), nullable=False))
    op.add_column('user_profile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('creationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'lastname')
    op.drop_column('user_profile', 'id')
    op.drop_column('user_profile', 'firstname')
    op.drop_column('user_profile', 'created_on')
    # ### end Alembic commands ###
