"""empty message

Revision ID: 7c9b73608463
Revises: 56a456600a04
Create Date: 2017-03-13 16:40:40.625636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9b73608463'
down_revision = '56a456600a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.Integer(), nullable=False))
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###
